### Book list
GET localhost:8080/book/list

### Book by id
GET localhost:8080/book/get/6

### Book create
POST localhost:8080/book/create
Content-Type: application/json

{
  "title": "Java",
  "author": "vali",
  "amount": "100",
  "visible": "true"
}
### Book update
PUT localhost:8080/book/update/7
Content-Type: application/json

{
  "title": "C++",
  "author": "Moxir"
}

### Book delete
DELETE localhost:8080/book/delete/1