### StudentBook create
POST localhost:8080/student-book/take
Content-Type: application/json

{
  "bookId": 3,
  "studentId": 1
}

### StudentBook update
PUT localhost:8080/studentBook/update/{{id}}
Content-Type: application/json

{
}

### StudentBook list
GET localhost:8080/studentBook/list

### Student Delete
DELETE localhost:8080/student/delete/1